export const RELEASE_GIT_TOKEN_ENV = "RD_GIT_TOKEN";
export const RELEASE_GIT_USERNAME_ENV = "RD_GIT_USERNAME";
export const RELEASE_GIT_REPOSITORY_URL_ENV = "RD_GIT_REPOSITORY_URL";
export const RELEASE_GIT_TARGET_BRANCH_ENV = "RD_GIT_TARGET_BRANCH";

export const RELEASE_GIT_AUTH_ENV_NAMES = [
  RELEASE_GIT_TOKEN_ENV,
  RELEASE_GIT_USERNAME_ENV,
  RELEASE_GIT_REPOSITORY_URL_ENV,
  RELEASE_GIT_TARGET_BRANCH_ENV,
] as const;
